### ISSUE TITLE
Help requested (again)

### ISSUE THREAD

**Issue by el97** [jphilll/AsusRouterMonitor#4]
I managed to get the authentication working as i mentioned in #3 but now I got another kind of error and it repeats. I have looked carefully and I think I have all the dependencies installed.
```
/usr/local/lib/python3.9/site-packages/apscheduler/util.py:95: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  if obj.zone == 'local':
/usr/local/lib/python3.9/site-packages/apscheduler/triggers/interval.py:66: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(next_fire_time)
```
This is what I got in the log file
```
2022-02-06 01:24:56,800 - WARNING - Monitor Restarted.
2022-02-06 01:24:59,878 - ERROR - Job "getData (trigger: interval[0:00:02], next run at: 2022-02-06 01:25:00 CET)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/pi/GrafanaAsusRouterMonitor/asusMonitor.py", line 170, in getData
    coretemp2g = int(re.search(r'(?<=curr_coreTmp_2_raw = ")\d+', tempResult)[0])
TypeError: 'NoneType' object is not subscriptable
2022-02-06 01:24:59,879 - WARNING - Monitor interupted, restarting..
2022-02-06 01:24:59,897 - WARNING - Monitor Restarted.
```

**Comment by jphilll** [comment]
Can you find the core temperature in the control panel? If not, then this data is not presented.

**Comment by el97** [comment]
I am able to see the core temperature of my router using the merlin software. It looks like it changes error message every time I run the code as well. Based on the code I can see that some of the URL's for data might not be the same for me. update.cgi that represents the speedURL gets me right to the login screen if I to http://192.168.1.1/update.cgi. Could that be the issue?

**Comment by jphilll** [comment]
Yes, you have to modify the code to adapt to your firmware.

**Comment by el97** [comment]
What is the best way to adapt? I can see what the code is expecting from the url but how do I figure out what url to use for the latest merlin firmware?

**Comment by jphilll** [comment]
Press F12 when you’re on the webpage showing the temperature, click on the ‘network’ tab and find which URL replies with the temperature. Do you have experience on web scraping?

**Comment by el97** [comment]
Not really..

**Comment by jphilll** [comment]
Well…there’s not much I can do here, there are differences from firmware to firmware, if not versions to versions
